src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $user_password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_Email = null;

    #[ORM\Column(length: 255)]
    private ?string $user_login = null;

    #[ORM\ManyToMany(targetEntity: Role::class, mappedBy: 'user_role')]
    private Collection $Users_Roles;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $user_ImagePath = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    public function __construct()
    {
        $this->Users_Roles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getUserPassword(): ?string
    {
        return $this->user_password;
    }

    public function setUserPassword(string $user_password): self
    {
        $this->user_password = $user_password;

        return $this;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_Email;
    }

    public function setUserEmail(?string $user_Email): self
    {
        $this->user_Email = $user_Email;

        return $this;
    }

    public function getUserLogin(): ?string
    {
        return $this->user_login;
    }

    public function setUserLogin(string $user_login): self
    {
        $this->user_login = $user_login;

        return $this;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUsersRoles(): Collection
    {
        return $this->Users_Roles;
    }

    public function addUsersRole(Role $usersRole): self
    {
        if (!$this->Users_Roles->contains($usersRole)) {
            $this->Users_Roles->add($usersRole);
            $usersRole->addUserRole($this);
        }

        return $this;
    }

    public function removeUsersRole(Role $usersRole): self
    {
        if ($this->Users_Roles->removeElement($usersRole)) {
            $usersRole->removeUserRole($this);
        }

        return $this;
    }

    public function getUserImagePath(): ?string
    {
        return $this->user_ImagePath;
    }

    public function setUserImagePath(?string $user_ImagePath): self
    {
        $this->user_ImagePath = $user_ImagePath;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\EditUserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class HomeController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    // #[Route('/', name: 'home')]
    public function index(): Response
    {
        // $serializer = Serializer::create()->build();
        $repository = $this->em->getRepository(User::class);

        $users = $repository->findAll();

        // dd($users);
        return $this->render(
            'home/index.html.twig',
            array('users' => $users)
        );
    }

    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(EditUserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function delete($id)
    {

        $user = $this->em->getRepository(User::class)->find($id);

        if (!$user) {
            throw $this->createNotFoundException('No user found for id ' . $id);
        }

        $this->em->remove($user);
        $this->em->flush();

        $this->addFlash('success', 'User deleted successfully!');

        return $this->redirectToRoute('home');
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home
{% endblock %}

{% block body %}
	{{ include('header/index.html.twig') }}
	<div class="container" id="main-container">
		<div class="row mt-5">
		{% for user in users %}
			<div class="col-md-6 col-xl-3">
				
					<div class="card m-b-30">
						<div class="card-body row">
							<div class="col-6">
								<a href=""><img src="{{user.userImagePath}}" alt="" class="img-fluid rounded-circle w-60"></a>
							</div>
							<div class="col-6 card-title align-self-center mb-0">
								<h5>{{user.firstname}}</h5>
								<p class="m-0">{{user.lastname}}</p>
							</div>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item">
								<i class="fa fa-envelope float-right"></i>Email :
								<a href="#">{{user.userEmail}}</a>
							</li>
							<li class="list-group-item">
								<i class="fa fa-phone float-right"></i>Phone :
								{{user.phone}}</li>
						</ul>
						<div class="card-body">
							<div class="float-right btn-group btn-group-sm">
								<a class="btn btn-primary tooltips" data-placement="top" href="{{ path('user_edit', { 'id': user.id }) }}" data-original-title="Edit">
									<i class="fa fa-pencil"></i>
								</a>
								<a class="btn btn-primary tooltips" data-placement="top" href="{{ path('user_delete', { 'id': user.id }) }}" data-original-title="Edit">
									<i class="fa fa-times"></i>
								</a>
							</div>
							<ul class="social-links list-inline mb-0">
								<li class="list-inline-item">
									<a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="" data-original-title="Facebook">
										<i class="fa fa-facebook-f"></i>
									</a>
								</li>
								<li class="list-inline-item">
									<a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="" data-original-title="Twitter">
										<i class="fa fa-twitter"></i>
									</a>
								</li>
								<li class="list-inline-item">
									<a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="" data-original-title="Skype">
										<i class="fa fa-skype"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				
			</div>
			{% endfor %}
		</div>
	</div>

{% endblock %}

{# 
	{% extends 'base.html.twig' %}

	{% block body %}
		<div class="container">
			<h1>User List</h1>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Email</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for user in users %}
						<tr>
							<td>{{ user.firstName }}</td>
							<td>{{ user.lastName }}</td>
							<td>{{ user.userEmail }}</td>
							<td>
								<a class="btn btn-primary tooltips" data-placement="top" href="{{ path('user_edit', { 'id': user.id }) }}" data-original-title="Edit">
									<i class="fa fa-pencil"></i>
								</a>
								<a href="{{ path('user_delete', {'id': user.id}) }}" class="btn btn-danger">Delete</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% endblock %} #}